name: Rust CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 6500:5432
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password123
          POSTGRES_DB: rust_sqlx

    env:
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 6500
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: rust_sqlx
      DATABASE_URL: postgresql://admin:password123@localhost:6500/rust_sqlx?schema=public

    steps:
      - name: Set up Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install PostgreSQL client
        run: sudo apt-get install -y postgresql-client

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          cargo build --verbose
          cargo test --verbose