name: Deploy to Cloud

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: your_docker_hub_username/your_app_name:latest

      - name: Deploy to Railway
        run: |
          curl -fsSL https://get.railway.app | bash
          railway login --github --token ${{ secrets.RAILWAY_TOKEN }}
          railway up